### ISSUE TITLE
Migrate to Native Craft 5 2FA?

### ISSUE THREAD

**Issue by brandonjjon** [born05/craft-twofactorauthentication#101]
I've done a bit of exploration here but is it possible at all to migrate or convert existing users 2FA codes over to Craft 5's native 2FA implementation? Or will I need to just uninstall this plugin and let them re set up 2FA from scratch. A lot of effort was put into getting users on board with this plugin here, so trying to minimize and disruptions to users in that regard if possible.

**Comment by roelvanhintum** [comment]
The implementation of Craft seems to be a lot nicer, so i prefer not to mess with that. My advice would be to uninstall the plugin and let users setup 2FA with Craft itself, which is pretty straight forward when 2FA is enforced.
