### ISSUE TITLE
Please provide examples on how to eneable frontend 2FA

### ISSUE THREAD

**Issue by dennisadriaans** [born05/craft-twofactorauthentication#18]
Hi, i would like to see some examples on how to enable 2FA for the frontend.

Especially for the frontEndPathWhitelist and/or blacklist settings.

You provide already two example templates for settings and verify. Which of them is the " 2FA form" you refer to in step 1.

**Comment by roelvanhintum** [comment]
@dennisadriaans Just enhanced the docs and examples to make things easier.

**Comment by dennisadriaans** [comment]
Works like a charm!
