### ISSUE TITLE
No option to blacklist the homepage from 2FA

### ISSUE THREAD

**Issue by dennisadriaans** [born05/craft-twofactorauthentication#20]
When you want to disallow access to the homepage e.g: domain.com/ without path,
users will get redirected to the verification page but can manually go back to the homepage without verification.

**Comment by roelvanhintum** [comment]
Does blacklisting an empty path work?

```
'frontEndPathBlacklist' => [
    '*' => [
        '', // Home path
    ],
],
```

**Comment by dennisadriaans** [comment]
No, did try three options. 

    // Blacklist paths that do need 2FA.
    'frontEndPathBlacklist' => [
        '*' => ['/', ' ', ''],
    ],

**Comment by roelvanhintum** [comment]
What does pathInfo return if you dump it? We match the value of `Craft::$app->getRequest()->getPathInfo();` to the array values of frontEndPathBlacklist.

https://github.com/born05/craft-twofactorauthentication/blob/master/src/services/Request.php#L143

**Comment by dennisadriaans** [comment]
string(0) "".

**Comment by dennisadriaans** [comment]
Maybe it is the CraftSpecialRequest path. 

https://github.com/born05/craft-twofactorauthentication/blob/master/src/services/Request.php#L164

**Comment by roelvanhintum** [comment]
Should work from 2.0.0-beta.12

**Comment by dennisadriaans** [comment]
Confirmed

**Comment by dennisadriaans** [comment]
Seems to be back.

Case: Login as user in the front-end when FA activated. Don't enter an authentication code from your phone. Instead type the homepage url in the address bar.

The browser will redirect the user without the need to enter an authentication code.

**Comment by roelvanhintum** [comment]
@dennisadriaans I'm getting logged out as supposed to, when login is required on home.

When login is not required on home, i'm allowed to visit, because 2FA only checks when login is required. Visit a page that does require login and the plugin logs you out because verification is missing.

**Comment by dennisadriaans** [comment]
Tested it several times, unfortunately, both the frontend and the backend login can be skipped by manually changing the URL after initial login.

**Comment by dennisadriaans** [comment]
It was conflcting with a custom Craft module.

**Comment by roelvanhintum** [comment]
@dennisadriaans allowFrontend was incorrectly in the readme, this should be verifyFrontEnd.
Make sure verifyFrontEnd is set to true. allowFrontend is not a thing.

**Comment by roelvanhintum** [comment]
@dennisadriaans to match home the following should be enough as a blacklist:

```
'frontEndPathBlacklist' => [
    '*' => [''],
],
```
