### ISSUE TITLE
Stable Release Date

### ISSUE THREAD

**Issue by matt-adigital** [born05/craft-twofactorauthentication#22]
Not really an issue, more of a question, but any ideas of when a stable release might happen for the Craft 3 version?

We want to use this for a client of ours but aren't too keen on using software which is still in beta as we'd like to avoid as many bugs as possible. Looks like a great plugin though, good work!

**Comment by roelvanhintum** [comment]
@matt-adigital Thanks! We're doing some in depth security tests in the coming week. Once those clear, i'll release it as stable. Shouldn't take more than two weeks.

**Comment by roelvanhintum** [comment]
@matt-adigital Just released 2.0.0
