### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by rinusvandam** [born05/craft-twofactorauthentication#29]
I have a website running two-factor authentication.

When I click the disable 2FA in the back-end for a user I get the following error:

`SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`passwordprotectedwebsite`.`twofactorauthentication_session`, CONSTRAINT `twofactorauthentication_session_sessionId_fk` FOREIGN KEY (`sessionId`) REFERENCES `sessions` (`id`) ON DELETE CASCADE)
The SQL being executed was: INSERT INTO `twofactorauthentication_session` (`userId`, `sessionId`, `dateVerified`, `dateCreated`, `uid`, `dateUpdated`) VALUES (3, 0, '2019-02-28 12:06:45', '2019-02-28 12:06:45', 'f1410a70-0a99-41bf-8af9-f8c59de7c492', '2019-02-28 12:06:45')`

I'm running:
- Craft Pro 3.1.15
- PHP 7.2.10
- Two-Factor Authentication 2.1.0

**Comment by roelvanhintum** [comment]
Fixed in 2.1.1

**Comment by rinusvandam** [comment]
Wow that's fast. Thanks!
