### ISSUE TITLE
rememberedUserSessionDuration of false causes crash

### ISSUE THREAD

**Issue by brybeecher** [born05/craft-twofactorauthentication#3]
The craftCms config value of [`rememberedUserSessionDuration`](https://craftcms.com/docs/config-settings#rememberedUserSessionDuration) being set to `false` instead of a time (eg. `'P1D'`) causes the following php error.

`Exception: DateInterval::__construct(): Unknown or bad format () in /var/www/craft/plugins/twofactorauthentication/services/TwoFactorAuthentication_VerifyService.php:41`
(see [source](https://github.com/born05/craft-twofactorauthentication/blob/master/services/TwoFactorAuthentication_VerifyService.php#L41))

Perhaps a sane default value for `$sessionDuration` when `rememberedUserSessionDuration` is false would be good? A few hours or a day perhaps?

**Comment by roelvanhintum** [comment]
@brybeecher thanks, i'll look into this.

**Comment by roelvanhintum** [comment]
fixed in 8571b5e8117760ceea606938c40c95215ecfd354
