### ISSUE TITLE
Craft 3.1 support

### ISSUE THREAD

**Issue by tonymilne** [born05/craft-twofactorauthentication#31]
Liking what you're doing with this plugin - keep up the great work!
I'd be keen to see the 3.1 branch get over the line and merged + released.

In the mean time i am directly installing from the latest commit in your craft-3.1 branch; if anyone else with this issue wants to do the same, here's what i added to my composer.json file:

```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/born05/craft-twofactorauthentication"
    }
  ],
```
and 
```
"born05/craft-twofactorauthentication": "dev-craft-3.1#b5bbd6347df74ae4f5814d30225a9fa0da4362aa"
```

**Comment by roelvanhintum** [comment]
@tonymilne guess you found it, but 2.1.x has Craft 3.1 support (indeed it does come from the 3.1 branch.
