### ISSUE TITLE
Settings page for "delayed auth"

### ISSUE THREAD

**Issue by EternalBlack** [born05/craft-twofactorauthentication#33]
This is meant as an enhancement suggestion:
I often find my self trying to log-in with a "just in that moment"-expired 2FA code. Using a password manager that automatically copies the 2FA code to my clipboard and me just pasting it in, without knowing how much time there is left.

As far as I can tell some other services already do something like that where they allow a recently expired key to still be valid.

Would be nice to have something like:
```
$current = $totp->verify($otp);
$delayed = $totp->verify($otp, time() - 5);
```
as validation.

Where `5` would ideally be set via a settings page of the plugin itself (or config file).

**Comment by roelvanhintum** [comment]
@EternalBlack the point of time-based two-factor authentication is that the codes are quickly invalidated. So, i don't think this change would be a good thing.
This would also block those same tools which happen to be really quick, because the start and end get a 5 second offset.

**Comment by EternalBlack** [comment]
I do know that in terms of security this is anything but wise to do and I'm not pressing that this should be `on` by default. Quoting Wikipedia might be questionable but I'll still do it:

> Both the authenticator and the authenticatee compute the TOTP value, then the authenticator checks if the TOTP value supplied by the authenticated matches the locally-generated TOTP value. Some authenticators allow values that should have been generated before or after the current time in order to account for slight clock skews, network latency and user delays.

[Source](https://en.wikipedia.org/wiki/Time-based_One-time_Password_algorithm) _as of 05.04.19_

I currently use
```php
$current = $totp->verify($otp);
$delayed = $totp->verify($otp, time() - 5);
if (!($current || $delayed)) {
	die('You cannot access this resource');
}
```
myself and it works fine for me. I can still access the resource with n OTP that is already invalid for 5 seconds. Undoubtedly this adds a padding to start **and** end in regards of generating a TOTP ahead of time that shouldn't be valid just yet.
Adding this to the [two-factor-authentication.php](https://github.com/born05/craft-twofactorauthentication/blob/master/examples/two-factor-authentication.php) would have been nice though - `off` by default, but there as an option for people that might want to use it.
Something like `allowedOffset => null` where `null` doesn't allow any offset and otherwise the given `Int` in seconds.
By no means I'd advise people to use a number as high as `5` seconds. As said, this was suggested as an option and not to be `on` by default. In my opinion it's about convenience for people that might experience similar things or just have a bad connection etc. This is no justification but as far as I can tell Google and other big companies do it the same way as in the end for them it's probably all about what the "feeling" is to the person that uses their service.

**Comment by roelvanhintum** [comment]
I guess, making it configurable wouldn't be an issue. I'll look into this today.

**Comment by roelvanhintum** [comment]
@EternalBlack version 2.1.2 has the totpDelay option.

**Comment by EternalBlack** [comment]
@roelvanhintum Awesome! Thank you!
