### ISSUE TITLE
Config Options Explanation

### ISSUE THREAD

**Issue by kgrote** [born05/craft-twofactorauthentication#34]
Thanks for this plugin! Could you explain what these config options do?

'verifyFrontEnd'
'forceFrontEnd'
 'forceBackEnd'

**Comment by roelvanhintum** [comment]
@kgrote, sorry for the late response. That does need some documentation. `verifyFrontEnd` allows verification when logging in front-end (non cp) users. see: https://github.com/born05/craft-twofactorauthentication#setting-up-front-end-2fa

`forceFrontEnd` and `forceBackEnd` force users to setup 2FA for their account.
