### ISSUE TITLE
Usergroups empty after disabling 2FA

### ISSUE THREAD

**Issue by RichardJong** [born05/craft-twofactorauthentication#36]
As an admin, when I disable 2FA for a user, the page reloads.
When a user belongs to a user group, this group is now unchecked. So if I save the current user, it is removed from that user group.

However when I reload the page, the user is correctly in the user group (and is correctly saved).

Maybe a bug within Craft?

*ps: thanks again for this great plugin

**Comment by roelvanhintum** [comment]
@RichardFrontwise thanks!

I'm guessing this is a Craft bug, since we don't change the user. We keep the 2FA data in out own separate tables. Disabling doesn't even redirect, but fires an action and let Craft resolve the url.

I'm seeing the same bug in Craft CMS 3.2.10
