### ISSUE TITLE
DateInterval::__construct(): Unknown or bad format if userSessionDuration set to 0

### ISSUE THREAD

**Issue by romainpoirier** [born05/craft-twofactorauthentication#37]
Using this setting value in my `config/general.php` file:
`'userSessionDuration' => 0, // users will stay logged in as long as its browser is open`
[https://docs.craftcms.com/v3/config/config-settings.html#usersessionduration](https://docs.craftcms.com/v3/config/config-settings.html#usersessionduration)

I get this error:
`Exception DateInterval::__construct(): Unknown or bad format (PT-1S)`

`born05/craft-twofactorauthentication/src/services/Verify.php` @ line 54:
`$minimalSessionDate->sub(new DateInterval('PT' . $sessionDuration . 'S'));`

`craft-twofactorauthentication` version: 2.2.0

**Comment by roelvanhintum** [comment]
@romainpoirier That is one of the requirements: "userSessionDuration in the general.php config should be larger than 0"
As discussed in #23
