### ISSUE TITLE
Can't login as user with 2FA enabled

### ISSUE THREAD

**Issue by Tam** [born05/craft-twofactorauthentication#40]
When attempting to login as a user from the CP the following error is thrown

```
Unauthorized

User is not permitted to perform this action
```

from the action `admin/actions/two-factor-authentication/settings/force`.

Versions:
- Craft Pro 3.4.5
- Two-Factor Authentication 2.4.0

**Comment by roelvanhintum** [comment]
Hi @Tam, are you sure the user has the correct rights? "Access the control panel" should be checked.
If not, can you provide me the the plugin config file you used?

**Comment by alexjcollins** [comment]
@roelvanhintum Thanks for the quick reply. What we're trying is to log in as a user **without control panel access**, and this used to work until, I think, [this update](https://github.com/born05/craft-twofactorauthentication/commit/c61ba5aaf94a69a3a15644692c26319651fd9705)).

The old behaviour user to send us on to the front end, now it throws that error.

Does that help?

**Comment by roelvanhintum** [comment]
@alexjcollins i'm not sure what happens, but the fact that the user is redirected to the `force` page means that the following line is reached [Request.php#L96](https://github.com/born05/craft-twofactorauthentication/blob/craft-3.1/src/services/Request.php#L96)

I could check both request type and user type to make sure non-cp users are redirected to the frontend. Out of curiosity: Do you use the admin login for frontend users?

**Comment by alexjcollins** [comment]
@roelvanhintum Yeah, it's weird! And, as I said, it used to work fine 🤷‍♂️

No, we have a separate login for users on the frontend. The 'Login as User' feature is only used by super admins to help users out when they have an issue with their account.

**Comment by roelvanhintum** [comment]
@alexjcollins can you test the `feature/non-cp-login-redirect` branch? This should fix your problem.

**Comment by alexjcollins** [comment]
@roelvanhintum Yes! that has resolved it. Thanks so much for sorting so quickly 🎉
