### ISSUE TITLE
Question regarding security

### ISSUE THREAD

**Issue by zsackett-dixonschwabl** [born05/craft-twofactorauthentication#41]
We're trying to evaluate 2fa options for Craft and had questions regarding this plugin's exact functionality. It's using EVENT_AFTER_LOGIN to create the redirect, but would it prevent the execution of controller actions, for example?

I see in issue #22 there's a reference to "in depth security tests", but haven't seen exactly what that entails. Thanks.

**Comment by roelvanhintum** [comment]
For every request the 2Fa plugin verifies the user from the plugin init, so this would prevent controllers from executing code. This is next to the EVENT_AFTER_LOGIN event.

For multiple clients we had pentests done and still do for every project. Unfortunately i can't share any details.

**Comment by zsackett-dixonschwabl** [comment]
Thanks for the reply!
