### ISSUE TITLE
Array to string conversion error

### ISSUE THREAD

**Issue by romainpoirier** [born05/craft-twofactorauthentication#43]
After upgrading from `2.2.0` to `2.6.1 `and changing `frontEndPathWhitelist` to `frontEndPathAllow` + `frontEndPathBlacklist` to `frontEndPathExclude` (following breaking change since `2.6.0`) I got this error on front-end:

```
PHP Notice – yii\base\ErrorException
Array to string conversion

/vendor/born05/craft-twofactorauthentication/src/services/Request.php
if ($this->isRegex("/$path/i")) { // line 150
```

Reverting to `frontEndPathBlacklist` + `frontEndPathBlacklist` fix this. I am wrong or I still was supposed to use allow/exclude in favor of whitelist/blacklist like I did?

**Comment by roelvanhintum** [comment]
@romainpoirier the frontEndPathWhitelist and frontEndPathBlacklist are ignored, so that is why the error disappears.

The old config had some issues with environments within variables, maybe that is the issue here? This is now only in the following format (notice the * at the top instead of inside the variable):

```php
<?php

return [
    '*' => [
        // Choose between using the accept or exclude! Using both will block everything!
        // Allow paths that do not need 2FA. Exact path or regex. No leading slashes.
        'frontEndPathAllow' => [
            'example-path',
        ],
        // Exclude paths that do need 2FA. Exact path or regex. No leading slashes.
        'frontEndPathExclude' => [
        ],
    ],

    'development' => [
        // Dev config overrides here
    ],

    'production' => [
        // Prod config overrides here
    ],
];
```

**Comment by romainpoirier** [comment]
I'm not using environments variables in my `two-factor-authentication.php`settings file (which got the error like explained):
```
<?php

return [
    'verifyFrontEnd' => true,
    'forceFrontEnd' => false,
    'forceBackEnd' => true,

    // The URI we should use for 2FA on the front-end.
    'verifyPath' => '2fa',
    
    // The URI we should use for 2FA settings on the front-end.
    'settingsPath' => '',

    // Choose between using the whitelist or blacklist! Using both will block everything!
    'frontEndPathAllow' => [
        '*' => [],
    ],
    'frontEndPathExclude' => [
        '*' => [],
    ],
];
```

So I understand I should finally write it like that as from `2.6.0` to get the same result:
```
<?php

return [
    '*' => [
        'verifyFrontEnd' => true,
        'forceFrontEnd' => false,
        'forceBackEnd' => true,

        // The URI we should use for 2FA on the front-end.
        'verifyPath' => '2fa',
        
        // The URI we should use for 2FA settings on the front-end.
        'settingsPath' => '',

        // Choose between using the accept or exclude! Using both will block everything!
        // Allow paths that do not need 2FA. Exact path or regex. No leading slashes.
        'frontEndPathAllow' => [],

        // Exclude paths that do need 2FA. Exact path or regex. No leading slashes.
        'frontEndPathExclude' => [],
    ],
];
```

This works without getting any error. Back-end should be always protected, whereas areas in front-end that required login and check if the user is an admin should enable 2FA (that's why the `*`).

**Comment by roelvanhintum** [comment]
That is correct. This should work. You can even omit everything that is same as default, similar to general.php
