### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by jordikroon** [born05/craft-twofactorauthentication#56]
Hi there!

Will this plugin receive an update for Craft 4? Built-in Craft 4 support for 2FA has been postponed until at least Craft 4.1, so this plugin is still relevant for us.

**Comment by jordikroon** [comment]
Should have checked the branch list first. 😓 

So the question changes a little. When do you expect to release the first beta version?

**Comment by roelvanhintum** [comment]
@jordikroon, yesterday ;)
I haven't ran it on any production sites yet, so that is why it's beta. Once it's confirmed to work fine on Craft 4, i'll release it as stable.

https://github.com/born05/craft-twofactorauthentication/releases/tag/3.0.0-beta.1
