### ISSUE TITLE
Feature Request: Enable/Disable 2FA for certain user groups

### ISSUE THREAD

**Issue by manuelthaler** [born05/craft-twofactorauthentication#57]
At the moment the enabling/disabling feature in the user editor is only visible for admins. do you see any chance to implement a feature to allow certain groups (these who are taking care of the community) to disable/enable the 2fa in the backend?

Either as a setting in the `two-factor-authentication.php`setting by adding the group id, or by using the regular permissions setting of craft?

**Comment by roelvanhintum** [comment]
@manuelthaler, seems like a good feature. I would do this with a permission setting.

**Comment by sadmachine** [comment]
@roelvanhintum We could definitely use a feature like this. We have a scenario where some craft CMS users need to use SSO, and others need to use 2FA. It would be ideal to be able to only enable 2FA for a specific group of users, and the rest can just use SSO to login. Unfortunately right now the 2FA is actually preventing the SSO from working entirely if we have `forceBackend` set to true, but we also need to force specific users to use 2FA, so someway to pick and choose would be very helpful.
