### ISSUE TITLE
Rename 2fa in Google auth

### ISSUE THREAD

**Issue by billymedia** [born05/craft-twofactorauthentication#58]
How do you set the label name in the google authenticator app?
When i scan the qr code, it sets the code number label to "Craft CMS (email@email.com)"
Can i change this to the company name?

**Comment by roelvanhintum** [comment]
@billymedia, this should be done using the general Craft CMS settings. Which versions are you using?

**Comment by roelvanhintum** [comment]
Correction: the email should be the user’s email.

**Comment by billymedia** [comment]
Craft 4.0.3
Plugin 3.0.0-beta.1

I have craft named under Settings > General as the clients name, but it labelled it as Craft CMS in google auth app, is there another settings somewhere i need to change?

**Comment by billymedia** [comment]
@roelvanhintum similar issue here https://github.com/born05/craft-twofactorauthentication/issues/60 

The reason is that in services/Verify.php on line 155, the issuer is being set to ```Craft::$app->name``` whereas it should be set to ```Craft::$app->sites->currentSite->name```

**Comment by roelvanhintum** [comment]
@billymedia user accounts and 2fa are system wide, not limited to one site. The line should be `Craft::$app->getSystemName()`

**Comment by roelvanhintum** [comment]
Fixed in 3.0.0
