### ISSUE TITLE
Impersonating Users

### ISSUE THREAD

**Issue by adampatpattison** [born05/craft-twofactorauthentication#65]
We've recently implemented this plugin and set `forceBackEnd` to `true`. 

Admin's or other users with the "Impersonate Users" permission are now asked to either setup 2FA or enter the user they're impersonating's verification code. 

Is there a way to subvert this when using the CraftCMS impersonate user option?

**Comment by roelvanhintum** [comment]
Sorry for the late response, but it i think it comes with to much vulnerabilities to change this behavior.
