### ISSUE TITLE
Verify login valdation prevents 2FA code from validating

### ISSUE THREAD

**Issue by ddnetters** [born05/craft-twofactorauthentication#68]
The authentication flow in the control panel doesn't work. It's caused by the 2FA code verification request being blocked by login validation.

**Environment**

- PHP 8.0
- Craft 4.3.1
- Two-Factor Authentication 3.0.1
- No custom configuration

**Steps to reproduce**

1. Setup a craft 4 environment with one user
2. Disable CSRF validation in the general config `->enableCsrfProtection(false)`, to circumvent #64.
3. Install and enable the 2FA plugin
4. Allow users to set 2FA without making it a strict requirement
5. Logout and login again (via the control panel), opening the network inspector of your browser
6. The `requireLogin() / allowAnonymous` controller validation blocks the request to the verify controller actions

**Suspected cause**
[Craft::$app->getUser()->logout(false);](https://github.com/born05/craft-twofactorauthentication/blob/craft-4/src/services/Request.php#L34) seems to be called before hitting [actionLoginProcess()
](https://github.com/born05/craft-twofactorauthentication/blob/craft-4/src/controllers/VerifyController.php#L30)

**Comment by roelvanhintum** [comment]
@ddnetters what do you mean by "Require login validation" on step 6?

**Comment by ddnetters** [comment]
After login you get redirect to `/index.php?p=admin/actions/two-factor-authentication/verify/login`, which shows the 2FA code verification form. When I submit that form without CSRF protection, I get the following response:
```json
{
	"name": "Forbidden",
	"message": "Login Required",
	"code": 0,
	"error": "Login Required",
	"status": 403,
	"exception": "yii\\web\\ForbiddenHttpException",
	"file": "/Users/dominique/clientname/vendor/yiisoft/yii2/web/User.php",
	"line": 461,
	"trace": [{
		"file": "/Users/dominique/clientname/vendor/craftcms/cms/src/web/Controller.php",
		"line": 367,
		"function": "loginRequired",
		"class": "yii\\web\\User",
		"type": "->"
	}, {
		"file": "/Users/dominique/clientname/vendor/craftcms/cms/src/web/Controller.php",
		"line": 150,
		"function": "requireLogin",
		"class": "craft\\web\\Controller",
		"type": "->"
	}, {
		"file": "/Users/dominique/clientname/vendor/yiisoft/yii2/base/Controller.php",
		"line": 176,
		"function": "beforeAction",
		"class": "craft\\web\\Controller",
		"type": "->"
	}, {
		"file": "/Users/dominique/clientname/vendor/yiisoft/yii2/base/Module.php",
		"line": 552,
		"function": "runAction",
		"class": "yii\\base\\Controller",
		"type": "->"
	}, {
		"file": "/Users/dominique/clientname/vendor/craftcms/cms/src/web/Application.php",
		"line": 301,
		"function": "runAction",
		"class": "yii\\base\\Module",
		"type": "->"
	}, {
		"file": "/Users/dominique/clientname/vendor/craftcms/cms/src/web/Application.php",
		"line": 625,
		"function": "runAction",
		"class": "craft\\web\\Application",
		"type": "->"
	}, {
		"file": "/Users/dominique/clientname/vendor/craftcms/cms/src/web/Application.php",
		"line": 280,
		"function": "_processActionRequest",
		"class": "craft\\web\\Application",
		"type": "->"
	}, {
		"file": "/Users/dominique/clientname/vendor/yiisoft/yii2/base/Application.php",
		"line": 384,
		"function": "handleRequest",
		"class": "craft\\web\\Application",
		"type": "->"
	}, {
		"file": "/Users/dominique/clientname/web/index.php",
		"line": 15,
		"function": "run",
		"class": "yii\\base\\Application",
		"type": "->"
	}, {
		"file": "/Users/dominique/.composer/vendor/laravel/valet/server.php",
		"line": 234,
		"function": "require"
	}]
}
```

So when the page gets returned, the user session gets forcefully ended. I suspect by [Craft::$app->getUser()->logout(false);](https://github.com/born05/craft-twofactorauthentication/blob/craft-4/src/services/Request.php#L34)

**Comment by roelvanhintum** [comment]
That logout line is to prevent users from visiting other pages before being verified, since the plugin can't really hook into the auth system. The user itself is logged in by craft at the login screen regardless of 2fa. The plugin can only logout users when 2fa isn't entered yet.

Your issue seems to be getting logged out within seconds, probably before posting the form. What happens when you refresh the form, so not submitting the 2fa code.

**Comment by ddnetters** [comment]
The session length is set to a year and removing [Craft::$app->getUser()->logout(false);](https://github.com/born05/craft-twofactorauthentication/blob/craft-4/src/services/Request.php#L34) resolves the bug. Are there any other mechanism within craft or the plugin that affect the authentication state?

**Comment by roelvanhintum** [comment]
Not that i know of. Removing the logout function from the plugin also makes the plugin useless, because 2fa isn't enforced anymore after that change.

**Comment by ddnetters** [comment]
Yes, that makes sense. I'm not trying to suggest removing the function call is a solution to the bug. I'm trying to work to a solution together for which we need to find a cause. No other sign-out mechanism is present, as far as we know. Removing that function call resolves the bug. It then seems reasonable to check whether the bug is being caused by the context wherein it's being called.

I haven't had the time for testing it thoroughly however it's seem like [Craft::$app->getUser()->logout(false);](https://github.com/born05/craft-twofactorauthentication/blob/craft-4/src/services/Request.php#L34) is being called in the same lifecycle as the verification form page gets rendered. Or perhaps it gets called before the verification ajax request reaches the controller function.

**Comment by joshuapease** [comment]
I recently ran into a similar situation on a project. 

Turns out that having the Yii Debug bar turned on for a users preferences was causing issues with the Authentication Code step.

The Yii Debug bar makes a extra web request before I could enter the Authentication Code.

I don't know for sure yet, but it seems like validate request gets called before entering the code, which immediately logs out the Craft users.

By the time I enter the Auth Code, I'm already logged out. 

Disabling these debug bar options for my user resolved my issue.

<img width="930" alt="image" src="https://user-images.githubusercontent.com/2145998/222306312-2323a9bb-8d5b-4bf6-871f-e03e63d63d27.png">

**Comment by Franqqq** [comment]
> I recently ran into a similar situation on a project.
> 
> Turns out that having the Yii Debug bar turned on for a users preferences was causing issues with the Authentication Code step.
> 
> The Yii Debug bar makes a extra web request before I could enter the Authentication Code.
> 
> I don't know for sure yet, but it seems like validate request gets called before entering the code, which immediately logs out the Craft users.
> 
> By the time I enter the Auth Code, I'm already logged out.
> 
> Disabling these debug bar options for my user resolved my issue.
> 
> <img alt="image" width="930" src="https://user-images.githubusercontent.com/2145998/222306312-2323a9bb-8d5b-4bf6-871f-e03e63d63d27.png">

This fixed it for me.
