### ISSUE TITLE
Logged out after 5s login page admin

### ISSUE THREAD

**Issue by oxochenxa** [born05/craft-twofactorauthentication#69]
When update plugin, i usually logged out after 5s login admin. Can you help me check it?

_Originally posted by @oxochenxa in https://github.com/born05/craft-twofactorauthentication/issues/67#issuecomment-1319680794_

**Comment by Romanavr** [comment]
Same issue
Clearing local storage usually helps.

**Comment by roelvanhintum** [comment]
@oxochenxa do you have the same problem when using an incognito window? I've had in the past some issues with existing/old sessions.
