### ISSUE TITLE
Unable to login, redirects back to login

### ISSUE THREAD

**Issue by Romanavr** [born05/craft-twofactorauthentication#70]
From time to time I can’t log in, right after logging in I am redirected back again to the login page
Cleaning up local storage, incognito mode and changing the browser work as temporary solutions

**Comment by ezawadzki** [comment]
@Romanavr what are the version you use of the package and craft ?

**Comment by Romanavr** [comment]
> @Romanavr what are the version you use of the package and craft ?

Craft Pro 3.7.56
Plugin 2.10.0

**Comment by roelvanhintum** [comment]
@Romanavr, sorry i've missed this. Can you update the plugin to 2.10.1 ? The event when logged in users are verified has changed, to make sure sessions etc are loaded. Hopefully this fixes the problem.

**Comment by LinneaHarts** [comment]
This is happening intermittently to me and a client. He has one email that can't use 2FA at all, and another one that fails intermittently. I'm finding mine only works on the 2nd attempt.

Craft CMS 4.3.6.1 (was also happening on 4.3.5)
Plugin version 3.0.1

**Comment by roelvanhintum** [comment]
@LinneaHarts, if it fails just sometimes it can be caused by the time settings on the server and/or phone. If one is a few seconds off the window for entering is less than the normal 30 seconds.

**Comment by Romanavr** [comment]
> @Romanavr, sorry i've missed this. Can you update the plugin to 2.10.1 ? The event when logged in users are verified has changed, to make sure sessions etc are loaded. Hopefully this fixes the problem.

After the update, the problem only occurred 1 time, so I believe the update worked in my case.
Thanks for the help.
