### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by mkrigsman** [born05/craft-twofactorauthentication#71]
Some users cannot login. They successfully complete the initial setup with Google Authenticator. However, when trying to login, the spinner moves for a moment but then nothing happens. Using the latest version of the plugin 3.01 and Craft Pro 4.3.5

Any ideas on how to fix?

**Comment by mvanbeselaere** [comment]
Similar issue; Craft Pro 4.3.6, just downloaded and set up the plugin, I am stuck with an error 400 and a problem in a jQuery script when I hit that "Verify" button. Can't even login anymore.
![image](https://user-images.githubusercontent.com/102756666/211395418-ede9f9b9-34ba-4d6d-82b7-22eaa183c9fa.png)

**Comment by roelvanhintum** [comment]
It looks like an issue with csrf tokens, because craft is returning 400 (Bad request). I think this is the same issue as #64
