### ISSUE TITLE
GraphQL support?

### ISSUE THREAD

**Issue by anchovy** [born05/craft-twofactorauthentication#72]
We're developing a headless craft site - will this plugin work with GraphQl? If so, do you have any documentation/examples on how to set this up?

Thanks in advance.

**Comment by roelvanhintum** [comment]
Hi @anchovy, the plugin works fine next to graphql (we use it a lot for the control panel while serving content over graphql). However it does not do anything with graphql, as far as i know there is no user login through graphql in Craft CMS.
