### ISSUE TITLE
Two-Factor Authentication success but cannot redirect to dashboard

### ISSUE THREAD

**Issue by Kensamurai** [born05/craft-twofactorauthentication#74]
Craft CMS 4.3.6.1
Two-Factor Authentication 3.0.1

Two-Factor Authentication success but cannot redirect to dashboard and browser console returned a 404 error.
Checked the error is caused from VerifyController > actionLoginProcess > afterLogin (line 45), the login will work after commanded this line.
Any method can fix this? What is the purpose of this function (afterLogin) actually? Can I just command this function if it is not necessary?

**Comment by roelvanhintum** [comment]
Is this fixed with ~~3.3.0~~?

Edit: 3.3.1
