### ISSUE TITLE
Syntax Error in Migration Script

### ISSUE THREAD

**Issue by brianrivet-tilt** [born05/craft-twofactorauthentication#78]
Hi,

I'm trying to update the plugin from version 2.10.1 to 2.11.0 and when Craft tries to run migrations it trips the following error:

Exception 'ParseError' with message 'syntax error, unexpected '|', expecting ';' or '{''
in /storage/XXXXXX/www/staging_html/vendor/born05/craft-twofactorauthentication/src/Plugin.php:132

Can you help me resolve?

Thanks!

Brian

**Comment by mattias78** [comment]
Hi I'm having the same issue trying to update from version 2.10.1 to 2.11.0.

Craft CMS 3.8.9

Status: error

Response: {"name":"Exception","message":"syntax error, unexpected '|', expecting ';' or '{'","code":0,"error":"syntax error, unexpected '|', expecting ';' or '{'","exception":"ParseError","file":"/var/www/html/vendor/born05/craft-twofactorauthentication/src/Plugin.php","line":132,"trace":[{"file":"/var/www/html/vendor/composer/ClassLoader.php","line":428,"function":"Composer\\Autoload\\includeFile"},{"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"function":"spl_autoload_call"},{"file":"/var/www/html/vendor/craftcms/cms/src/services/Plugins.php","line":917,"function":"is_subclass_of"},{"file":"/var/www/html/vendor/craftcms/cms/src/services/Plugins.php","line":232,"function":"createPlugin","class":"craft\\services\\Plugins","type":"->"},{"file":"/var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php","line":1520,"function":"loadPlugins","class":"craft\\services\\Plugins","type":"->"},{"file":"/var/www/html/vendor/craftcms/cms/src/web/Application.php","line":99,"function":"_postInit","class":"craft\\web\\Application","type":"->"},{"file":"/var/www/html/vendor/yiisoft/yii2/base/BaseObject.php","line":109,"function":"init","class":"craft\\web\\Application","type":"->"},{"file":"/var/www/html/vendor/yiisoft/yii2/base/Application.php","line":204,"function":"__construct","class":"yii\\base\\BaseObject","type":"->"},{"function":"__construct","class":"yii\\base\\Application","type":"->"},{"file":"/var/www/html/vendor/yiisoft/yii2/di/Container.php","line":419,"function":"newInstanceArgs","class":"ReflectionClass","type":"->"},{"file":"/var/www/html/vendor/yiisoft/yii2/di/Container.php","line":170,"function":"build","class":"yii\\di\\Container","type":"->"},{"file":"/var/www/html/vendor/yiisoft/yii2/BaseYii.php","line":365,"function":"get","class":"yii\\di\\Container","type":"->"},{"file":"/var/www/html/vendor/craftcms/cms/src/Craft.php","line":61,"function":"createObject","class":"yii\\BaseYii","type":"::"},{"file":"/var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php","line":247,"function":"createObject","class":"Craft","type":"::"},{"file":"/var/www/html/vendor/craftcms/cms/bootstrap/web.php","line":51,"function":"require"},{"file":"/var/www/html/web/index.php","line":11,"function":"require"}]}

**Comment by roelvanhintum** [comment]
Which php version are you using? I think i accidentally added php 8.x syntax, which should just be in the Craft CMS 4 version of the plugin.

**Comment by roelvanhintum** [comment]
Is this solved with version 2.11.1 of the plugin?

**Comment by mattias78** [comment]
> Which php version are you using? I think i accidentally added php 8.x syntax, which should just be in the Craft CMS 4 version of the plugin.



I’m using PHP version | 8.1.17
-- | --

**Comment by brianrivet-tilt** [comment]
I'm running php 7.4.3, Craft 3.8.7

**Comment by roelvanhintum** [comment]
@mattias78 @brianrivet-tilt  Does version 2.11.1 solve the errors?

**Comment by brianrivet-tilt** [comment]
Yes that resolved the issue. Thanks!
