### ISSUE TITLE
2FA can be disabled without verifying 2FA token

### ISSUE THREAD

**Issue by Zae** [born05/craft-twofactorauthentication#80]
It's possible to disable a users 2FA authentication status if the user is already logged in, for example when a users forgets to logout.

Is it possible to ask for a valid 2FA token when disabling 2FA?

**Comment by roelvanhintum** [comment]
No, you currently cannot verify with a 2fa token when disabling.

**Comment by Zae** [comment]
Is this something that could be added to the roadmap of the plugin?

**Comment by roelvanhintum** [comment]
Sorry @Zae, I think Craft CMS itself is going to have 2FA in a short time, so there isn't much of a roadmap anymore.

**Comment by Zae** [comment]
HI @roelvanhintum ,

Thanks for letting me know! I'll just enable forceBackEnd until that option become available in craft then!
