### ISSUE TITLE
Outdated Description in Craft 4 Plugin Store

### ISSUE THREAD

**Issue by tomcollis** [born05/craft-twofactorauthentication#82]
The description for this plugin in the Craft 4 Plugin Store, available at: 

https://plugins.craftcms.com/two-factor-authentication?craft4

is out of date, it is currently:

Craft 3 plugin for two-factor or two-step login using Time Based OTP (TOTP, like Google Authenticator). Every user can setup TOTP themselves, the plugin does not force users. Admins can list usage in user tables.

Ideally it should be updated to:

Craft 4 plugin for two-factor or two-step login using Time Based OTP (TOTP, like Google Authenticator). Every user can setup TOTP themselves, the plugin does not force users. Admins can list usage in user tables.

**Comment by roelvanhintum** [comment]
Thanks @tomcollis! I've changed it to: "Plugin for two-factor or two-step login using Time Based OTP (TOTP, like Google Authenticator). Every user can setup TOTP themselves, the plugin does not force users. Admins can list usage in user tables."

I don't see the changes yet, but that's probably a cache layer.

**Comment by tomcollis** [comment]
Awesome, showing the update on the store page now. Thank you for the quick turnaround.
