### ISSUE TITLE
Plugin keeps redirecting to login screen while authentication code is correct

### ISSUE THREAD

**Issue by lineke** [born05/craft-twofactorauthentication#83]
Hi, we often have the issue that we fill in the password, then the authentication code and then it keeps redirecting back to the screen where you have to fill in the password. This happens quite often lately. We are already using version 3.2.0 of the plugin and one of the latest craft versions as well (4.4.14). Will be updating these both to the newest versions, but I am not sure this will solve the issue. 

We do not see any errors in the logging. Is there anything else what could happen?

**Comment by roelvanhintum** [comment]
Is this fixed with ~~3.3.0~~?

Edit: 3.3.1

**Comment by lineke** [comment]
I will update the plugin. It is kinda hard to reproduce, sometimes it happens twice a week and then it does not happen for another few weeks. So it might take some time before I can conclude that the issue is resolved. Thank you for your fast reply and the work at this awesome plugin!

**Comment by lineke** [comment]
Hi, we updated the plugin to the latest version and that works great with craft cms 4.4, but we also updated craft to 4.5 now and suddenly the plugin keeps returning a 400 Bad request when we try to login with 2FA enabled. Do you have an idea why this is?

**Comment by roelvanhintum** [comment]
Could be a corrupted session. Is it solved when you clear the cookies for your site?

**Comment by lineke** [comment]
Thanks @roelvanhintum for your fast reply! It seems to be, on my laptop it works fine but a colleague has this issue on his computer. He will check if this helps. Our QA can also login after restarting her macbook.

**Comment by Moorst** [comment]
I see this 400 issue too, on Craft 4.5.3 and 3.3.1 for the plugin.

Have tried in multiple browsers, no luck.

**Comment by roelvanhintum** [comment]
Lets move this to one issue #84, to hopefully faster solving the issue.
