### ISSUE TITLE
Feature Request: Backup Codes

### ISSUE THREAD

**Issue by KarlBishop** [born05/craft-twofactorauthentication#85]
A lot of other 2FA systems give the user a bunch of Backup Codes when activating, to use as an alternative login method in case the authenticator device is lost or unavailable.

I think this would be a great addition to the Two-Factor Authentication plugin, so a user in this situation may not have to wait for an Admin to come online to remove 2FA from their account for them.

**Comment by roelvanhintum** [comment]
Thanks @KarlBishop, this would be a great feature. Because of the upcoming native 2FA feature in Craft i'm a little hesitant to add this. It would involve a lot of work and we think this plugin is on it's way out.

**Comment by KarlBishop** [comment]
@roelvanhintum oh cool, good to hear 2FA is becoming native 👍
