### ISSUE TITLE
Does not allow you to login if "Show the debug toolbar in the control panel" is checked in user preferences

### ISSUE THREAD

**Issue by illiterati** [born05/craft-twofactorauthentication#88]
Hey there. Running Craft CMS 4.8.0, plugin version 3.3.6, and I can't login when I have "Show the debug toolbar in the control panel" checked in my User preferences. It asks for the authenticator code, but never approves it. Disabling the plugin, unchecking the box, and re-enabling the plugin works.

**Comment by roelvanhintum** [comment]
@illiterati, the debug toolbar does requests before 2fa authentication, causing the plugin to logout again. If these would be allowed, it would create a possible security vulnerability. You could turn of 2fa during development in the php settings file.

**Comment by illiterati** [comment]
This is probably something that should be mentioned in the Read Me, as I spent an hour debugging it this morning.
