### ISSUE TITLE
3.3.6 introduced UnknownMethodException `Request::isCraftSpecialRequests()`

### ISSUE THREAD

**Issue by qrazi** [born05/craft-twofactorauthentication#89]
I am very happy to create a PR, but I couldn't figure out how to access the plugin templates in 3.3.5, so not sure if:

- `shouldRedirectFrontEnd` should not call `$this->isCraftSpecialRequests()`
- or `private function isCraftSpecialRequests` should be restored to be used only by `shouldRedirectFrontEnd`

**Comment by roelvanhintum** [comment]
@qrazi thanks for reporting this! Sorry for the inconvenience. Fix is released in 3.3.7

**Comment by qrazi** [comment]
No worries, impressed by the quick response!
