### ISSUE TITLE
Can't log in after activating 2FA

### ISSUE THREAD

**Issue by jhubb-io** [born05/craft-twofactorauthentication#9]
Hey. I can't log in after activating 2FA. The process to activate works correctly then I log out. After logging in, I'm redirected to the 2FA input but clicking verify shows the progress indicator for about 200ms then nothing happens.

I've attached the logs.
[web-404s.log](https://github.com/born05/craft-twofactorauthentication/files/2162068/web-404s.log)
[web.log](https://github.com/born05/craft-twofactorauthentication/files/2162069/web.log)

**Comment by roelvanhintum** [comment]
@jhubb-io did the verify/login-process request give any feedback? It should show a message.

**Comment by RichardFrontwise** [comment]
Probably because you've enabled the debug toolbar for the Control Panel, experienced the same issue.

**Comment by jlamb1** [comment]
Same thing for me - Activation worked correctly, I signed out, signing back in shows the 2fa prompt. Entering the code produces a 403 error in the console and nothing happens. I also had the debug toolbar enabled for the control panel. I can't get into my account

**Comment by roelvanhintum** [comment]
I’ll try and push a fix for this, this morning. I’m guessing it’s something stupid i overlooked. 

@jlamb1 You can go into the database and remove the records from the twofactorauthentication_verify table. This will disable 2FA for those users.

**Comment by roelvanhintum** [comment]
Fixed in 2.0.0-beta.3

The debug bar triggered an extra request, which caused a logout.

**Comment by roelvanhintum** [comment]
see: dfce3375ed14699159885da815ea811062918014

**Comment by jhubb-io** [comment]
Excellent, thanks.
