### ISSUE TITLE
Unauthorised when trying to view impersonation URL.

### ISSUE THREAD

**Issue by harry2909** [born05/craft-twofactorauthentication#91]
We're trying to impersonate a user who **cannot** access the control panel. Once impersonated, it should redirect to the front end of the site.

The URL changes to /index.php/admin/actions/two-factor-authentication/settings/force

I can see the message: Unauthorised, User is not permitted to perform this action.

Our config is as follows:

```
return [
    '*' => [
        'totpDelay' => null,
        'verifyFrontEnd' => false,
        'verifyBackEnd' => true,
        'forceFrontEnd' => false,
        'forceBackEnd' => true,
        'verifyPath' => '',
        'settingsPath' => '',
        'backEndPathAllow' => [],
        'frontEndPathAllow' => [],
        'frontEndPathExclude' => [],
    ],
];

```

We're currently using version 2.11 on craft version 3.7.46. 
I'd appreciate any help on this. Thanks!

**Comment by roelvanhintum** [comment]
Hi @harry2909, sorry i cannot help with that version of Craft anymore. Does the same happen on Craft 4?

Please know that Carft 3 is soon reaching end of life.

**Comment by harry2909** [comment]
@roelvanhintum no problem, thanks for your message. We will look to upgrade.
