### ISSUE TITLE
Update for Craft 5

### ISSUE THREAD

**Issue by lineke** [born05/craft-twofactorauthentication#92]
Any idea when the plugin will be updated to use for Craft CMS version 5?

**Comment by roelvanhintum** [comment]
Hi @lineke, it won't. Craft 5 has native support for 2FA, which is also way nicer to work with. This plugin will become abandoned from Craft 5 forward.

**Comment by lineke** [comment]
@roelvanhintum Thanks for your response! How easy is it to upgrade to Craft 5 then?

**Comment by roelvanhintum** [comment]
That is mostly depending on other plugins. I would uninstall this plugin before doing so, just to be sure. Craft itself is pretty straight forward, but to be sure check: https://craftcms.com/docs/5.x/upgrade.html

Setting up Craft's two-factor authentication is explained here: https://craftcms.com/docs/5.x/system/user-management.html#time-based-one-time-passwords

**Comment by lineke** [comment]
Thanks!
