### ISSUE TITLE
Increase time before 2FA lockout

### ISSUE THREAD

**Issue by webdnaltd** [born05/craft-twofactorauthentication#94]
Hello,

We are looking into whether it is possible to increase the time before getting locked out when using the 2FA plugin. 
When looking in the plugin documentation we couldn't find a way to do this.

Is there currently an option available for increasing this time?
If not is it possible to add this functionality?

Many Thanks
Harry at webdna

**Comment by roelvanhintum** [comment]
@webdnaltd, this is handled by Craft's sessions. If this is too short, there can be a number of reasons. This is discussed before, which may help. For example: #42
