### ISSUE TITLE
2FA and SSO

### ISSUE THREAD

**Issue by paragonn** [born05/craft-twofactorauthentication#96]
Hi -- We are using SSO to allow users to log into Craft CMS, however, for the native Craft CMS login I want to add 2FA. We have tried to have the SSO plugin and the 2FA plugin running simultaneously but the SSO fails to work when the 2FA plugin is also installed. Is there a way to fix this?

**Comment by roelvanhintum** [comment]
Hi @paragonn, currently not. We ran into the same problem on Craft 4 ourselves and couldn't find a fix for this. I'm hoping the Craft 5 native 2FA solves this issue.
